# Generated by Django 5.2.7 on 2025-10-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='votes_count',
        ),
        migrations.AddField(
            model_name='application',
            name='work_image',
            field=models.ImageField(blank=True, null=True, upload_to='contest_works/', verbose_name='Работа (PNG)'),
        ),
    ]
