# Generated by Django 5.2.7 on 2025-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_vote_votes_count_application_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP заявителя'),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на портфолио'),
        ),
    ]
